### ISSUE TITLE
Data is not exporting.

### ISSUE THREAD

**Issue by bhargav-sudo** [JanKoppe/ffmpeg-exporter#1]
Hi @JanKoppe. I am using this tool. 
I ran a file with ffmpeg and stored the data into a .txt file (/tmp/ffmpeg)
After completion of ffmpeg progress.

I am exporting to an IP address. But it shows the output like this.
Why it isn't showing any data that is in my txt file.

![Screenshot from 2022-06-27 12-28-05](https://user-images.githubusercontent.com/57169077/175878491-955f21f8-acfa-4317-bc3c-6bed9b854cb3.png)

How does it works..? Please help me to make work on this.

Thanks.

**Comment by JanKoppe** [comment]
Hey! Thanks for trying this out :)

Can you show me the full command that you use to run the ffmpeg-exporter?

 Do note please, that the -i parameter expects a path to a directory that contains the progressfile, not the path to a single file.

 It sounds like you are writing the progress to a file called `/tmp/ffmpeg`, and then using the default location of `/tmp/ffmpeg` for the lookup with this exporter. This does not work, as `/tmp/ffmpeg` in this case is a file, not a directory. You'd need to write the ffmpeg progress to a file called e.g. `/tmp/ffmpeg/foobar`.

Then the exporter will pick up this `foobar` file, and expose the metrics with a `identifier="foobar"` label, so that you can distinguish between multiple processes.

**Comment by bhargav-sudo** [comment]
Hi thanks for the reply.
This is the command that i use to write process into a file.
**ffmpeg -i input.mp4 -vf scale=w=100:h=50 output.mp4 -progress /tmp/ffmpeg/myfancytranscodejob.txt**

my txt file.
[myfancytranscodejob.txt](https://github.com/JanKoppe/ffmpeg-exporter/files/9008261/myfancytranscodejob.txt)

This is the command that i use to run the ffmpeg exporter.
  **./ffmpeg-exporter.py -i /tmp/ffmpeg -p 1234**

It says this after running above command.
[INFO]: watching /tmp/ffmpeg

How can i run that.?

**Comment by JanKoppe** [comment]
Hm, that's weird. One thing to note: The exporter will ignore files with `progress=end`, which will happen once an ffmpeg process has finished. Your log indicates that the ffmpeg process was running for just ~7 seconds. Could it be that you requested the metrics after the ffmpeg process has finished already?

The primary usecase for this exporter was to have an eye on livestream transcodes. These are very long running ffmpeg processes (sometimes several days). For very short batch jobs (as in your case), this exporter might not be the best approach. Can you elaborate a bit on your use case?

**Comment by bhargav-sudo** [comment]
Hi. 
Our case is also the same primary usecase as you said. To record live metrics and expose live metrics. So, I will try to run this same on bigger video files tomorrow and let you know the state of this work. 

Thanks

**Comment by bhargav-sudo** [comment]
Hi @JanKoppe .

I tried this when my ffmpeg process is on live and it is sending the data to a file located in /tmp/ffmpeg.
But it shows this error while exporting.

**command** : 
./ffmpeg-exporter.py -i /tmp/ffmpeg -p 1234

**Error** : 

[INFO]: watching /tmp/ffmpeg
Traceback (most recent call last):
  File "./ffmpeg-exporter.py", line 102, in <module>
    REGISTRY.register(FfmpegCollector(args.watch_path))
  File "/.local/lib/python3.6/site-packages/prometheus_client/registry.py", line 26, in register
    names = self._get_names(collector)
  File "/.local/lib/python3.6/site-packages/prometheus_client/registry.py", line 66, in _get_names
    for metric in desc_func():
  File "./ffmpeg-exporter.py", line 77, in collect
    g_speed.add_metric([identifier], float(value.removesuffix('x')))
AttributeError: 'str' object has no attribute 'removesuffix'

**Comment by bhargav-sudo** [comment]
Hi. This has found in my searching.
[https://stackoverflow.com/questions/66683630/removesuffix-returns-error-str-object-has-no-attribute-removesuffix](url)

It says remove suffix is 3.9+ python version method in str. my python version is 3.6. So, I installed python3.9 and ran it again.
It works.
**Command** : 
python3.9 ffmpeg-exporter.py -i /tmp/ffmpeg -p 1234

![Screenshot from 2022-06-30 10-02-00](https://user-images.githubusercontent.com/57169077/176593381-12f584b1-010d-454c-9f28-f03f0869e8b1.png)

**Comment by JanKoppe** [comment]
Hm, nice catch. Will rework it to not rely on that method, as Python 3.7 and 3.8 are not EOL yet.

Thanks!

**Comment by JanKoppe** [comment]
Fixed with https://github.com/JanKoppe/ffmpeg-exporter/releases/tag/v0.1.1

**Comment by bhargav-sudo** [comment]
Thanks @JanKoppe :smile:
